name: Deploy promet.unitec.ac.mz

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Entrar na VPS e criar backup
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            PROJECT_DIR="/projects/promet/frontend/promet.unitec"
            BACKUP_DIR_PARENT="../"
            MAX_BACKUPS=5

            echo "Entrando no diretório do projeto..."
            cd $PROJECT_DIR || exit 1

            echo "Criando backup incremental (excluindo node_modules, .env e logs)..."
            BACKUP_DIR="${BACKUP_DIR_PARENT}promet.unitec.ac.mz_backup_$(date +%Y%m%d%H%M%S)"
            mkdir -p "$BACKUP_DIR"
            rsync -av --exclude 'node_modules' --exclude '.env' --exclude '*.log' ./ "$BACKUP_DIR/"

            echo "Removendo backups antigos..."
            cd $BACKUP_DIR_PARENT
            ls -1dt promet.unitec.ac.mz_backup_* | tail -n +$((MAX_BACKUPS+1)) | xargs -r rm -rf

      - name: Atualizar código na VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            PROJECT_DIR="/projects/promet/frontend/promet.unitec"
            cd $PROJECT_DIR || exit 1
            git fetch origin main
            git reset --hard origin/main || git pull origin main

      - name: Instalar dependências
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |

            PROJECT_DIR="/projects/promet/frontend/promet.unitec"
            cd $PROJECT_DIR || exit 1

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm use 20
            node -v
            npm install

      - name: Build do projeto
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            PROJECT_DIR="/projects/promet/frontend/promet.unitec"
            cd $PROJECT_DIR || exit 1
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm use 20
            node -v
            npm run build

      - name: Reiniciar PM2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            PROJECT_DIR="/projects/promet/frontend/promet.unitec"
            cd $PROJECT_DIR || exit 1
            pm2 restart promet.unitec.ac.mz || pm2 start npm --name "promet.unitec.ac.mz" -- start
            pm2 save
            echo " Deploy concluído com sucesso!"
